# Ephemeral Nessie Configuration (In-Memory Version Store)
versionStoreType: IN_MEMORY

image:
  tag: "0.107.0"
  pullPolicy: IfNotPresent

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

# Service configuration
service:
  type: ClusterIP

# Iceberg REST Catalog settings
catalog:
  enabled: true
  iceberg:
    defaultWarehouse: local
    warehouses:
      - name: local
        location: s3a://iceberg-data/
  storage:
    s3:
      defaultOptions:
        endpoint: "http://minio.minio.svc.cluster.local:9000"
        region: us-east-1
        pathStyleAccess: true
        authType: STATIC
        accessKeySecret:
          name: minio-creds
          awsAccessKeyId: rootUser
          awsSecretAccessKey: rootPassword
