# Postgres-Analytics Custom Values
# This DB stores the business/example data for Superset, separating it from Metadata DBs.

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "18.3.0"
  digest: sha256:9b62e6057d781853916a712ad2591a607de4529160e07c2eaf58d75ef6c45b9d
  pullPolicy: IfNotPresent

auth:
  username: analytics
  password: analytics
  database: analytics

primary:
  service:
    type: LoadBalancer
    ports:
      postgresql: 5433
  persistence:
    enabled: false
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resourcesPreset: "none"

volumePermissions:
  enabled: false
